# Generated by Django 2.0.7 on 2018-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0002_auto_20180409_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalaefollowup',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical AE Follow-up Report'},
        ),
        migrations.AlterModelOptions(
            name='historicalaeinitial',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical AE Initial Report'},
        ),
        migrations.AlterModelOptions(
            name='historicalaetmg',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical AE TMG Report'},
        ),
        migrations.AlterModelOptions(
            name='historicalrecurrencesymptom',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Recurrence of Symptoms'},
        ),
        migrations.AlterField(
            model_name='aefollowup',
            name='outcome',
            field=models.CharField(choices=[('continuing/update', 'Continuing/Update'), ('increase_from_g3', 'Severity increased from Grade III'), ('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving at end of study'), ('not_recovered', 'Not Recovered/Resolved at end of study'), ('LTFU', 'Unknown/Lost to follow-up'), ('recovered_with_sequelae', 'Recovered with sequelae')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='outcome',
            field=models.CharField(choices=[('continuing/update', 'Continuing/Update'), ('increase_from_g3', 'Severity increased from Grade III'), ('recovered', 'Recovered/Resolved'), ('recovering', 'Recovering/Resolving at end of study'), ('not_recovered', 'Not Recovered/Resolved at end of study'), ('LTFU', 'Unknown/Lost to follow-up'), ('recovered_with_sequelae', 'Recovered with sequelae')], max_length=25),
        ),
    ]
